version: '3'

services:
  dev:
    image: jekyll/jekyll:3.8.5
    command: jekyll serve --livereload
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - /tmp/jekyll:/usr/local/bundle
